name: CI-CD Pipeline

on:
  push:
    branches: [ master, test, prod]
  pull_request:
    branches: [ master, test, prod]

env:
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_ENV: ghcr.io
  IMAGE_REGISTRY: bantanger/achobeta

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull commit head^3
        uses: actions/checkout@v3

      - name: setup java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: checkout code
        uses: actions/checkout@v2

      - name: start build java project
        run: mvn clean install package -Dmaven.test.skip=true

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_ENV }}
          username: BanTanger # 使用仓库的拥有者名作为用户名
          password: ${{ secrets.GHCR_IO_TOKEN }} # 使用存储在 GitHub Secrets 中的 ghcr.io 的访问令牌

      - name: docker compose build and push
        run:
          # cd polaris-app
          # sudo sh build.sh
          docker build -t ${{ IMAGE_ENV }}/${{ env.IMAGE_REGISTRY }}/polaris:${{ env.IMAGE_TAG }} -f ./Dockerfile .

      - name: Push Image
        run:
          docker push ${{ IMAGE_ENV }}/${{ env.IMAGE_REGISTRY }}/polaris:${{ env.IMAGE_TAG }}